name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  just-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo this is cicd test 1
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: initialize project
        run: yarn install --frozen-lockfile
      - name: yarn app test
        run: yarn test
  ci_test_and_deploy_aws:
    runs-on: ubuntu-latest
    steps:
      - run: node -v
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: initialize project
        run: yarn install --frozen-lockfile
      - name: yarn app test
        run: yarn test
      - name: build time
        run: yarn build
      - name: deploy aws s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
          SOURCE_DIR: 'build'
